import type { EfficiencyReport } from "./efficiency.js";
import {
  leversFromReport,
  MEMORY_FLAG_LEVERS,
  renderMemoryBlock,
  type EfficiencyMemoryOptions,
  type MemoryFlagLever,
  type MemoryLevers
} from "./efficiencyMemory.js";

// Accumulative memory — instead of regenerating the AGENTS.md/CLAUDE.md block from
// ONLY the last run, accrue levers across runs so a pattern seen 10× ranks above a
// one-off, and stale lessons decay out. Pure: the daemon owns persistence.
//
// Model: every accrue() decays all existing weights, then adds the current run's
// levers (+1 each). An item seen every run converges to weight ~5; an item seen
// once decays below the prune floor after ~5 runs and drops. `count` is the raw
// number of runs that surfaced the item, used to annotate recurring ones.

export type ProfileItem = { label: string; weight: number; count: number };

export type EfficiencyProfile = {
  commands: ProfileItem[];
  reread: ProfileItem[];
  injections: ProfileItem[];
  bigReads: ProfileItem[];
  retries: ProfileItem[];
  flags: Record<string, { weight: number; count: number }>;
  seenRuns: string[]; // runIds already folded in — makes accrue idempotent (capped)
  updatedAt: string;
};

const DECAY = 0.8;
const PRUNE = 0.35; // drop items whose weight falls below this (≈ unseen for 5 runs)
const SEEN_CAP = 100;

export function emptyProfile(): EfficiencyProfile {
  return { commands: [], reread: [], injections: [], bigReads: [], retries: [], flags: {}, seenRuns: [], updatedAt: "" };
}

type ListKey = "commands" | "reread" | "injections" | "bigReads" | "retries";
const LIST_KEYS: ListKey[] = ["commands", "reread", "injections", "bigReads", "retries"];

function decayList(list: ProfileItem[]): ProfileItem[] {
  return list.map((i) => ({ ...i, weight: i.weight * DECAY })).filter((i) => i.weight >= PRUNE);
}

function addLabels(list: ProfileItem[], labels: string[]): void {
  for (const label of labels) {
    const existing = list.find((i) => i.label === label);
    if (existing) {
      existing.weight += 1;
      existing.count += 1;
    } else {
      list.push({ label, weight: 1, count: 1 });
    }
  }
}

/**
 * Fold a run's levers into the profile. Idempotent per runId (re-applying the same
 * run is a no-op), so previewing/applying repeatedly never double-counts.
 */
export function accrueProfile(
  profile: EfficiencyProfile,
  report: EfficiencyReport,
  options: EfficiencyMemoryOptions & { runId: string; ts: string }
): EfficiencyProfile {
  if (options.runId && profile.seenRuns.includes(options.runId)) return profile;
  const levers = leversFromReport(report, options);

  const next: EfficiencyProfile = {
    commands: decayList(profile.commands),
    reread: decayList(profile.reread),
    injections: decayList(profile.injections),
    bigReads: decayList(profile.bigReads),
    retries: decayList(profile.retries),
    flags: {},
    seenRuns: [options.runId, ...profile.seenRuns.filter((r) => r !== options.runId)].slice(0, SEEN_CAP),
    updatedAt: options.ts
  };

  addLabels(next.commands, levers.commands);
  addLabels(next.reread, levers.reread);
  addLabels(next.injections, levers.injections);
  addLabels(next.bigReads, levers.bigReads);
  addLabels(next.retries, levers.retries);

  // Decay then bump the flag levers.
  for (const [id, v] of Object.entries(profile.flags)) {
    const w = v.weight * DECAY;
    if (w >= PRUNE) next.flags[id] = { weight: w, count: v.count };
  }
  for (const id of levers.flags) {
    const cur = next.flags[id] ?? { weight: 0, count: 0 };
    next.flags[id] = { weight: cur.weight + 1, count: cur.count + 1 };
  }

  return next;
}

// Top labels for a list, ranked by weight, annotated "(×N)" when recurring.
function topLabels(list: ProfileItem[], n: number): string[] {
  return [...list]
    .filter((i) => i.weight >= PRUNE)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, n)
    .map((i) => (i.count >= 2 ? `${i.label} (×${i.count})` : i.label));
}

/**
 * Render the managed block from the accumulated profile — recurring levers ranked
 * first, one-offs already pruned by decay. Same templates as the single-run path.
 */
export function buildAccumulatedMemory(profile: EfficiencyProfile): string | null {
  const levers: MemoryLevers = {
    commands: topLabels(profile.commands, 4),
    reread: topLabels(profile.reread, 6),
    injections: topLabels(profile.injections, 4),
    bigReads: topLabels(profile.bigReads, 4),
    retries: topLabels(profile.retries, 4),
    flags: new Set<MemoryFlagLever>(
      MEMORY_FLAG_LEVERS.filter((id) => (profile.flags[id]?.weight ?? 0) >= PRUNE)
    )
  };
  return renderMemoryBlock(
    levers,
    "Auto-generated by Agent-Blackbox, accumulated across recent runs — frequent items (×N) rank first; one-offs fade. Put your own notes ABOVE this block."
  );
}

// Validate a parsed profile from disk (best-effort; bad shape → fall back to empty).
export function isEfficiencyProfile(v: unknown): v is EfficiencyProfile {
  if (typeof v !== "object" || v === null) return false;
  const p = v as Partial<EfficiencyProfile>;
  return (
    LIST_KEYS.every((k) => Array.isArray((p as Record<string, unknown>)[k])) &&
    typeof p.flags === "object" &&
    p.flags !== null &&
    Array.isArray(p.seenRuns)
  );
}
